### ISSUE TITLE
Error when i start bot

### ISSUE THREAD

**Issue by AntoDipp** [DaRealDorseyBro/discord-minigames#11]
Error:
node index.js
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module './battle'
Require stack:
- /home/runner/Bob-the-duck/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/runner/Bob-the-duck/index.js:2:24)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/Bob-the-duck/index.js' ]

**Comment by AntoDipp** [comment]
Ok, i resolved it bu now i have this error: Package operation failed.

**Comment by AntoDipp** [comment]
ok, i remove scr and the bot are now online! But it don't reply me

**Comment by AntoDipp** [comment]
the bot does not respond and does not report any errors; I added everything required

**Comment by AadiatAhmed** [comment]
Try this code
```const minigames = require('discord-minigames')

module.exports = {
    name: 'battle',
    description: 'duel',

    async run(client, message, args) {
        const member = message.mentions.members.first()
        if(!member) return message.channel.send("Whom you want to play with?")
        if(member.user.bot)return message.channel.send("Bots are not interested here.")

        minigames.startBattle( member, message )
    }
}
```

**Comment by DaRealDorseyBro** [comment]
alr
